name: chatoid
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.2.3
  flutter_staggered_animations: ^1.1.1
  flutter_zoom_drawer: ^3.2.0
  go_router: ^14.6.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  onesignal_flutter: ^5.2.6
  path: ^1.9.0
  provider: ^6.1.2
  quickalert: ^1.1.0
  reaction_askany: ^0.1.2
  rive: ^0.13.14
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.6.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/chatoid.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/animated_login.riv
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/loading_earth.gif
    - assets/chatoid.png
    - assets/girl1.gif
    - assets/girl2.gif
    - assets/girl3.gif
    - assets/profile.gif
    - assets/boy1.gif
    - assets/eye.gif
  uses-material-design: true
